### ISSUE TITLE
--features', type=str, default='M'

### ISSUE THREAD

**Issue by ooOPPPPPS** [OrigamiSL/FDNet2023#2]
Does this algorithm able to support MS mode use multivariate predict univariate, and I also try to use use_multi_gpu, but it doesn't work? should I modify somthing?

**Comment by OrigamiSL** [comment]
1st: No. As rarely do researches perform 'MS' forecasting, no corresponding implementation is included.
2nd: Neither does use_multi_gpu. I only used a simple GPU during experiments so that I removed the corresponding codes about using multiple GPUs. However, you can refer to the souce codes of Informer(https://github.com/zhouhaoyi/Informer2020), whose architecture is the one this work imitates, if you want to use multiple GPUs. Only minor modifications are needed.
