### ISSUE TITLE
Error when running traffic dataset and electricity dataset

### ISSUE THREAD

**Issue by vote9527** [OrigamiSL/FDNet2023#7]
Hello author, I encountered an error when running the traffic dataset and electricity dataset
  File "/root/FDNet/exp/exp_model.py", line 141, in train
    train_data, train_loader = self._get_data(flag='train')
  File "/root/FDNet/exp/exp_model.py", line 92, in _get_data
    data_set = Data(
  File "/root/FDNet/data/data_loader.py", line 273, in __init__
    self.__read_data__()
  File "/root/FDNet/data/data_loader.py", line 289, in __read_data__
    cols.remove(self.target)
ValueError: list.remove(x): x not in list
This seems to be caused by improper reading of data. Does the author have any solution?

**Comment by OrigamiSL** [comment]
Such problem can be bypassed if you read **README.MD** carefully:
**We place ETT in the folder `./ETT-data`, ECL in the folder `./electricity`, Exchange in the folder `./exchage_rate`, ILI in the folder `./illness`, Traffic in the folder `./traffic`  and weather in the folder `./weather` of [here](https://drive.google.com/drive/folders/1ZOYpTUa82_jCcxIdTmyr0LXQfvaM9vIy?usp=sharing) (the folder tree in the link is shown as below) into folder `./data` and rename them from `./ETT-data`,`./electricity`, `./exchange_rate`, `./illness`, `./traffic` and `./weather` to `./ETT`, `./ECL`, `./Exchange`, `./ILI`, `./Traffic` and`./weather` respectively. We rename the file of ECL/Exchange from `electricity.csv`/ `exchange_rate.csv`/ `national_illness.csv`/ `traffic.csv` to `ECL.csv`/ `Exchange.csv`/ `ILI.csv`/`Traffic.csv` and rename the last variable of ECL/Exchange/Traffic from `OT` to original `MT_321`/ `Singapore`/ `Sensor_861`.**

I kindly suggest that you might foremost refer to README.MD if you met bugs, whereas it is welcome to ask more questions here if you ensure that your problem is not relevant to the instructions in README.MD

**Comment by vote9527** [comment]
Thank the author for his quick and enthusiastic reply. The organizational form of the folder is consistent with the provided form, because the ETT and weather data sets can be run using scripts, but other data sets have run errors, the above run errors.

**Comment by OrigamiSL** [comment]
You may pay attention to the last sentence of the above paragragh:
**We rename the file of ECL/Exchange from electricity.csv/ exchange_rate.csv/ national_illness.csv/ traffic.csv to ECL.csv/ Exchange.csv/ ILI.csv/Traffic.csv and rename the last variable of ECL/Exchange/Traffic from OT to original MT_321/ Singapore/ Sensor_861.**
You shall manually modify the file names and **the last variable name** in the files, then your problem can be addressed.
Just as I said, you shall carefully read the README.MD.

**Comment by vote9527** [comment]
Thanks to the author for his continued replies. The problem has been solved. It was because I did not read the MD file carefully. Thanks again to the author. Finally, I would like to ask why the last column attribute name needs to be modified on other tables? Is it because of the format required for data reading?

**Comment by OrigamiSL** [comment]
Yes. 'OT' is the name of the last variable in ETT dataset and the authors of Autoformer, who provided the integrated datasets in the google drive, changed the last variable name of other datasets to 'OT' for the convenience on univariate forecasting. However, we recover the variables names in our usages for showing the respect to the data providers.
